# Generated by Django 4.2.4 on 2023-08-15 11:44

from django.db import migrations, models
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=rules.file_uploader.wrapper),
            preserve_default=False,
        ),
    ]
