# Generated by Django 4.2.4 on 2023-08-15 15:17

from django.db import migrations, models
import django.db.models.deletion
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image'),
        ('product', '0005_productimage_image_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=rules.file_uploader.wrapper),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
