# Generated by Django 4.2.4 on 2023-08-15 15:19

from django.db import migrations, models
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image_alter_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=rules.file_uploader.wrapper),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
