# Generated by Django 4.2.4 on 2023-08-12 21:31

import django.core.validators
from django.db import migrations, models
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=rules.file_uploader.wrapper),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='This field must contain a valid phone number in the format 01(1 or 2 or 5 or 0)XXXXXXXX', regex='^01(0|1|2|5)\\d{8}$')]),
        ),
    ]
