# Generated by Django 4.2.4 on 2023-08-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
