# Generated by Django 4.2.4 on 2023-08-15 11:44

from django.db import migrations, models
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_id_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=rules.file_uploader.wrapper),
        ),
    ]
