# Generated by Django 4.2.4 on 2023-08-15 16:00

from django.db import migrations, models
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=rules.file_uploader.wrapper),
        ),
    ]
