# Generated by Django 4.2.4 on 2023-08-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('On Hold', 'On Hold')], default='Pending', max_length=15),
        ),
    ]
